### PR TITLE
Add an autoresizing mask to each subview

### PR DESCRIPTION
**Pull request by robrix**
This fixes the introduction of 0-width/-height `NSAutoresizingMaskLayoutConstraint`s.

### CODE REVIEW

**Comment by mdiep** [comment]
> This fixes the introduction of 0-width/-height `NSAutoresizingMaskLayoutConstraint`s.

Under what conditions to these appear? :confused:

**Comment by robrix** [comment]
> Under what conditions do these appear? :confused:

`xib` loading. In a new app, with a fresh `xib`, split view subviews have autoresizing masks like so:

```
<autoresizingMask key="autoresizingMask"/>
```

In `GitHub.GHChangesetViewController.xib`, which IIRC I initially created as non-auto layout, and then migrated to auto layout later on, the split view subviews have autoresizing masks like so:

```
<autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
```

In fact, damn near every view does, including the split view itself. None of the problem views have the `translatesAutoresizingMaskIntoConstraints` attribute set, so it defaults to `YES`, and when AppKit loads the `xib`, it blindly obeys these settings and the result is havoc.

The fresh `xib` does have some autoresizing masks set on some views; clip views and table cell views both have this autoresizing mask:

```
<autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
```

Therefore, we probably can’t just find & replace across the whole `xib`, and fixing in `MDPSplitView` is an easy workaround. That suggests that this may not be quite the right fix. However, if we try to mimic the fresh `xib` by setting `translatesAutoresizingMaskIntoConstraints` to `NO` and `autoresizingMask` to `NSViewNotSizable` in `didAddSubview:`, it’s already too late: the constraints appear to be in place (or else we’re being countermanded by something in the guts of `NSSplitView`).

Another interesting angle on this is that given a broken constraint such as this:

```
"<NSAutoresizingMaskLayoutConstraint:0x600000a98ec0 h=--& v=&-- V:[NSView:0x608000124d80(0)]>"
```

we can explore from there to the split view, and ask it how it feels about this whole state of affairs:

```
(lldb) p (NSView *)0x608000124d80
(NSView *) $9 = 0x0000608000124d80
(lldb) po [$9 superview]
<MDPSplitView: 0x60800035ad00>
(lldb) p (BOOL) [[$9 superview] _splitViewUseConstraintBasedLayout]
(BOOL) $11 = NO
```

One way or another, things are pretty broken by the time we the exception is thrown.

**Comment by robrix** [comment]
Hm, the `_splitViewUseConstraintBasedLayout` result may be specific to my branch—apparently I’m still implementing the delegate methods which trigger that in this view controller. For shame!

**Comment by robrix** [comment]
Yeah, that was it. So we can (and I shall) set the subviews up like so:

```objc
subview.translatesAutoresizingMaskIntoConstraints = NO;
subview.autoresizingMask = NSViewNotSizable;
```

**Comment by robrix** [comment]
Actually, that fixes the problem in this particular view already. So, nothing to see here! :disappointed:

**Pull request closed without merging**
